train:
    epochs: 120
    batch_size: 32
    lr: 0.0001
    num_workers: 10

    patience: ${train.epochs} # No early stopping (patience == epochs)
    consecutive_trains: 5

    step_scheduler: true
    scheduler: "linear" # linear, cosine, polynomial or reducelronplateau
    warmup_steps: 0.1

    weight_decay: 0.01

    optimizer: "adam" # adam or adan

feature_extractor:
    sample_rate: 32000
    mel_bins: 128
    target_length: 512

data_augmentation:
    use_audio_mixup: true
    mixup_alpha: .5

    use_specaug: true
    freqm: 48
    timem: 96

    rand_sampling: true

    insert_noise: false

model:
    ckpt: "pretrained_models/chunk_patch_75_12LayerEncoder.pt"
    classes_num: 15
    pretrained: false
    freeze_base: false
    encoder_embedding_dim: 768

data:
    seeds: [34385, 45840, 62400, 2646, 38844]
    behavior: both
    period: 2

    data_path: ../../
    preloaded_data_path: ../../segmented_preloaded_data/Bees_blueberry_2020_and_2021_updated
    dataset_csv_path: ../../data/blueberry_chile/metadata/planilla_MADRE_2021+2022_los_rios+maule.xlsx

    spec_norm_mean: 4.26
    spec_norm_std: 4.57

    frac_train: 0.50
    frac_test: 0.50
    output_dir: weights/MAEAST-5x2cv-patch-${train.optimizer}-${train.scheduler}-${model.pretrained}_pretrained-${data_augmentation.use_audio_mixup}_mixup-${data_augmentation.use_specaug}_specaug-${data_augmentation.rand_sampling}_randsamp-${train.epochs}_epochs-${feature_extractor.target_length}
    # output_dir: weights/MAEAST-5x2cv-patch-True_pretrained-True_audio_mixup-True_specaug-True_rand_sampling-False_insert_noise-300_epochs-512-0.5-48-96

metadata:
    especies_column_name: "especie"
    genre_column_name: "genero"
    audio_name_column_name: "audio"
    begin_time_column_name: "begin time (s)"
    end_time_column_name: "end time (s)"
    behavior_column_name: "behavior"

scores:
    scores_path: ../../scores-20_21

