wget -c "https://zenodo.org/records/3987831/files/Cnn14_mAP%3D0.431.pth" -O "models/cnns/panns/pretrained_weights/Cnn14_mAP=0.431.pth"
wget -c "https://www.dropbox.com/s/d1z27wj30ew5qrs/as_mdl_0.pth" -O "models/cnns/psla/pretrained_weights/as_mdl_0.pth"
wget -c "https://www.dropbox.com/s/ca0b1v2nlxzyeb4/audioset_10_10_0.4593.pth" -O "models/transformers/ast/pretrained_weights/audioset_10_10_0.4593.pth"
wget -c "https://www.dropbox.com/s/ewrzpco95n9jdz6/SSAST-Base-Patch-400.pth" -O "models/transformers/ssast/pretrained_weights/SSAST-Base-Patch-400.pth"
wget -c "https://www.cs.utexas.edu/~harwath/model_checkpoints/mae_ast/chunk_patch_75_12LayerEncoder.pt" -O "models/transformers/mae_ast/pretrained_weights/chunk_patch_75_12LayerEncoder.pt"